### ISSUE TITLE
The output of miccai_2018.py

### ISSUE THREAD

**Issue by white-hy** [voxelmorph/voxelmorph#122]
Hi! Dear author. Great work! I am using voxelmorph for pulmonary image registration
I trained the model using `miccai2018.py`, and then registered a pair of images using` register.py`. 
The ` register.py` outputs the `warp image` and the `displacement vector field`. My image size is `224x144x192`. 
I noticed the size of  `warp image` size is `224x144x192`, and  the size of  `displacement vector field` size is `112x72x96x6`. I'm a bit confused. 
1. Why is the size of  `displacement vector field` `112x72x96x6` instead of `224x144x192x3`? 
2. What does a displacement vector field of size `112x72x96x6` mean?
3. Can I get a `displacement vector field` of size `224x144x192x3`, just like cvpr model.

**Comment by adalca** [comment]
Hello @white-hy 

The miccai model outputs the **velocity field parameters**. These are, essentially, the velocity field mean and the uncertainty (standard deviation) around that. Since both are 3D, together they are 6 channels. The reason they are half the size is because we estimate them at every 2 voxels (for memory limitations).

To get the displacement field, you can look at how we deal with it in `test_miccai2018.py`. Specifically, you can use 

```
diff_net = keras.models.Model(net.inputs, net.get_layer('diffflow').output)
```

Where net is your `miccai2018_net`. The output of this new model is the deformation field only. Does this make sense?
