### ISSUE TITLE
train_img_template error

### ISSUE THREAD

**Issue by theoVag** [voxelmorph/voxelmorph#130]
Hello,
I am trying to create an unconditional atlas from my data but I get the following error:
https://pastebin.com/7j20KaXq

I am running the train_img_template with the parameters:
python3 voxelmorph-master/src/train_img_template.py "$main_path/main_preprocess/data_corrected/train/vols" \
	--atlas_file "$main_path/atlas_dir/9052335_atlas.npz" \
	--model_dir "$main_path/voxelmorph-master/models" \
	--load_model_file "$main_path/voxelmorph-master/models/template/miccai2018_10_02_init1.h5" \
	--gpu 0 \
	--lr 0.0001 \
	--epochs 600 \
	--batch_size 1 \
	--prior_lambda 10 \
	--image_sigma 0.02 \
	--mean_lambda 1 \
	--data_loss "mse" \
	--lambda 0.01 \
	--initial_epoch 0

Do you have any idea about the error?
Thanks a lot in advance

**Comment by adalca** [comment]
@theoVag this is caused by a change in keras behaviour, where the `output_layers` is no longer a property in keras after a certain release version. 

can you try replacing the `mod_submodel` function from  `/home/tpvagenas/voxelmorph-master/ext/neuron/neuron/utils.py` with the one from `https://github.com/adalca/neuron/blob/master/neuron/utils.py` ? It will fix the references to those entities.

**Comment by theoVag** [comment]
Thanks now it works!
