### ISSUE TITLE
Details about KL loss and λ parameter

### ISSUE THREAD

**Issue by tychovdo** [voxelmorph/voxelmorph#150]
Dear @adalca , (and other authors),

First of all, thank you for your research contributions.

Currently, I am trying to understand the ELBO loss used in the [MICCAI 2018](http://www.mit.edu/~adalca/files/papers/miccai2018_voxelmorph-pd.pdf) and [MedIA 2019](https://arxiv.org/abs/1903.03545) papers and I have two questions about the details:

1. Why is the KL term averaged over volume size instead of summed?
2. Why is setting λ=10000 equivalent to a diagonal standard deviation of 1 voxel for phi_z?

Examples of averaging are here:

https://github.com/voxelmorph/voxelmorph/blob/699d754f2ffb6b7a73aa471c83d510f1ac2d3268/src/losses.py#L228

and

https://github.com/voxelmorph/voxelmorph/blob/699d754f2ffb6b7a73aa471c83d510f1ac2d3268/src/losses.py#L198

I can imagine this averaging helps to keep the KL term in sensible range. However, I do not find any references of such averaging in the [MICCAI 2018](http://www.mit.edu/~adalca/files/papers/miccai2018_voxelmorph-pd.pdf) and [MedIA 2019](https://arxiv.org/abs/1903.03545) papers. For as far as I understand the derivations, the averages should be summations. It would be nice if you could elaborate on this?

Another thing is that in the [MICCAI 2018](http://www.mit.edu/~adalca/files/papers/miccai2018_voxelmorph-pd.pdf) paper it is mentioned that "the lambda factor is set to 10 000, which is equivalent to a diagonal standard deviation of 1 voxel for phi_z". To me, lambda would be the precision of the gaussian prior. It is not completely clear to me how a precision of 10 000 matches a standard deviation of 1 voxel in phi_z.

Very much looking forward to hearing your thoughts about this. 

Best, Tycho

**Comment by adalca** [comment]
hi @tychovdo ,

1. you're right, it's not in the paper because it's not a detail that affects the optimization -- we're just dividing the losses by a scalar (the volume size) so that we can understand the printed values better. Changing these means to sums won't affect the behavior

2. Your intuition is right. This was because of a discrepancy in our implementation with our math (which I believe we fixed in the MedIA paper) -- at the time, the network was predicting the scaled velocity field in 'scaling and squaring'. I don't recall the exact details, but as a back-of-the-envelope calculation, with lambda ~ 10000 you would get a variance of roughly 2/(6*10000), (6 because of the degree of grid connections) so standard deviation = 0.08. This was the variance of the *scaled* velocity, scaled by the number of integration steps: `2^nb_steps` = 128, so the real standard deviation is 0.08*128 = 1 (roughly).
