### ISSUE TITLE
Regarding multi-modal losses (Mutual Information (MI) and its local version) 

### ISSUE THREAD

**Issue by boveiri** [voxelmorph/voxelmorph#161]
Thanks for your time and energy spend to keep this forum updated.

I have some questions regarding multi-modal losses (Mutual Information (MI) and its local version) in the updated losses.py.

The definition of MI loss function is as follows:

`def globalMutualInformation(bin_centers,
                      sigma_ratio=0.5,
                      max_clip=1,
                      crop_background=False):`

That is, it needs bin_centers as the primary parameters, yet I would like the function to get the number of bins as input and produce the center of bins accordingly.

My input is **paired** float32 CT and MR images normalized to mean=0 and std=1, and I want to keep this normalization. In addition, 16 bins I am intended to have to compute the MI. The question is that:

1) should I create the center of bins for each pair of CT/MR, for batch or for whole the dataset? considering the CTs and MRIs have been captured by some different devices. I mean creating the center of bins statically for whole the dataset may not be a good idea. I do not know!

2) As the inputs are in float32, the center of bins are also in the float cast. Is this OK?

Thanks and regards,

**Comment by adalca** [comment]
@boveiri ,

1. In the current implementation, the bin centers have to be dataset-wide unless you change the code so that the bin_centers is a Tensor that is an input at each batch -- but this requires bigger changes to the code, including the model. As it stands, it's dataset wide. I don't think it's a big issue though, even if your data is heterogeneous -- if an image has a different intensity profile, it will be reflected in the soft histogram based on the bins, which is what you would want.

2. Yup sounds good.

**Comment by boveiri** [comment]
Thank you for your timely response and the information provided.

I think it may be helpful to exemplify: I have 495 pairs of 2D CT/MR slices from 60 subjects (volumes or patients). After normalization, considering whole the dataset, the CTs fall in the range of [-1.72, 6.90], but the MRs are in the range of [-0.93, 10,69].

If 16 bins is to be considered, what is your suggestion to select as the bins_centers? I mean e.g. from -1.72 to -0.93 there are not any voxels in MRs. On the other hand, from 6.90 to 10.69 there are not any voxels in the CTs.

Thanks and regards,

**Comment by adalca** [comment]
I would choose something like `np.linspace(all_data.min(), all_data.max(), nb_bins)` where all_data is all your data, MR and CT, together.

Regarding your example, the mutual information is implemented in a soft way (otherwise you wouldn't be able to get gradients, so you'd have to use a different optimization). The implementations we chose will always put *some* weight in *each* bin, based on an exponential drop-off. Therefore I wouldn't worry about empty bins.
