### ISSUE TITLE
about the code

### ISSUE THREAD

**Issue by ahuczp** [voxelmorph/voxelmorph#17]
I have read your code.,so I have some question? first,Does the ”flow“ in the code means  the dense registration field? Second,how to resample the moving image,I could understand the messure in your paper ,but I  can not understand your code.Could you explain your code detailed. Thank you very much!

**Comment by adalca** [comment]
Yup, we sometimes refer to the dense correspondance as `flow` in the code.

I'm nto sure I understand your question "how to resample the moving image" -- we use `neuron.layers.SpatialTransformer` from the [neuron](https://github.com/adalca/neuron/) repository to transform an image -- is this what you mean?

**Comment by ahuczp** [comment]
when I use the CC  as loss，the loss does not decrease,instead increase? why?Thankn you for help me.

**Comment by adalca** [comment]
The total loss increases, or just the data term? The total loss should not increase -- can you give more details about what you are doing?

**Comment by ahuczp** [comment]
I used the trained model to make predictions on the test data set. According to the mse and cc indicators, the registration result is better, but the printed image shows that the result of the registration is worse from a visual point of view. Yes, what is the reason?Thank you.

**Comment by ahuczp** [comment]
Hey，I need your help ,could you please help me ? thank you very much.

**Comment by ahuczp** [comment]
where can I download the ADNI dataset (Post-Processed MRI using FreeSurfer），I can not find the download link in LONI webset.Can you help me ? Thank you !

**Comment by adalca** [comment]
Here is the data access application: http://adni.loni.usc.edu/data-samples/access-data/
And after you are given permission, the link is here: https://ida.loni.usc.edu/login.jsp
Unfortunately, we can't provide our own pre-processed data due to data agreements, but you should be able to use VoxelMorph without too much processing. Try, for example, simple normalizing the intensities and then training a VoxelMorph model.
