### ISSUE TITLE
[Question] about NCC loss

### ISSUE THREAD

**Issue by vincentme** [voxelmorph/voxelmorph#177]
I just noticed that the equation and code used by voxelmorph to calculate NCC_loss is actually calculated the NCC_loss**2. This substitute is beneficial for computation(through convolution). However, in theory, the ncc_loss of two complete inverse image is -1 and its square is 1, which indicates using this equation may not give the right direction in rare cases. 

What do you think of this?

**Comment by adalca** [comment]
I think this is a matter of definition, we've gotten accustomed to defining the LNCC cross correlation function with the square in it (see Avants 2008 and the CC papers it cites), mostly because the focus was on having a robust measure for within-modality registration (but robust to noise, bias field, etc).  

Although I have to think about this more carefully, I think the non-square version could still be cleanly and easily implemented with convolutions with slight modifications on our code, if you wanted, but I guess you should ask in which cases you would like to use that in?

**Comment by vincentme** [comment]
Thank you. Yes, I just realize that the computation to calculate the non-square version is not more expensive than the squared one. 

I thought of one case that the non-square version is more appropriate: in the image with periodic structures/patterns, the squared cc could lead the deformation field of a windowed image pattern into the middle of two patterns that the calculated NCC is still 1. 

Actually I don't see any disadvantage of using the non-squaared NCC. It does not introduce the ambiguity and the computation is similar. Right?
