### ISSUE TITLE
bw_grid behaviour changed

### ISSUE THREAD

**Issue by riccardosamperna** [voxelmorph/voxelmorph#187]
Hi Adrian (@adalca),

I was recently trying to use again the bw_grid to visualize a vector field but it looks like that something changed in the behaviour of numpy (I am using numpy 1.18). I am not able to get a nice grid anymore and I am also not sure about the correctness of the implementation. 
You recently added a thickness parameter but I think the thickness should be taken into account also in this line:
https://github.com/adalca/pytools-lib/blob/7013bcc40b686bf94eb5bd2f2de2793cc1711660/pynd/ndutils.py#L134
and in line:
https://github.com/adalca/pytools-lib/blob/7013bcc40b686bf94eb5bd2f2de2793cc1711660/pynd/ndutils.py#L135
there is a warning about deprecation that I guess could be solved by using tuple() for indexing.

This is a small example:
`grid_img = bw_grid((128, 256, 512), 10)
plt.imshow(grid_img[55, :, :], cmap='gray')`
![example1](https://user-images.githubusercontent.com/6599726/81430463-bc94a400-915f-11ea-9dd7-a0e8f609d8d8.png)

`grid_img = bw_grid((128, 256, 512), 10)
plt.imshow(grid_img[: , 55, :], cmap='gray')`
![example2](https://user-images.githubusercontent.com/6599726/81430518-d635eb80-915f-11ea-9dd1-f9d8a850ae61.png)

`grid_img = bw_grid((128, 256, 512), 10)
plt.imshow(grid_img[: , :, 55], cmap='gray')`
![example3](https://user-images.githubusercontent.com/6599726/81430588-f1086000-915f-11ea-80d5-31835ce9aeb6.png)

**Comment by adalca** [comment]
Hi @riccardosamperna 

I always appreciate this sort of feedback. However, in this case I don't quite understand:
I don't quite see how that line should change? The very reason why there is a loop is to achieve the thickness.

I also don't fully understand what you are highlighting in the example? If it's the inconsistency in the spacing , I think this is an issue with how matplotlib is showing the image (it needs to do some interpolation since the image is too big to show in that figure axis). You can crop some part of the image to see that it's consistent.

Or were you trying to show that lines are not thick? You didn't give it a thickness value in those calls, so it defaults to 1.

Am i misunderstanding?

**Comment by riccardosamperna** [comment]
Hi @adalca,
As always, thanks a lot for your availability and your quick reply.
I think I got tricked by the visualization of matplotlib, I was getting those strange grids and I did not understand what exactly was going on. I thought that something changed in the indexing of numpy due to the FutureWarning.

One thing I am still confused of is that when I create this small example:
`test_grid = bw_grid((5, 5, 5), 1)`
and I visualize it with matplotlib, I get a black image.

My intuition would tell me that I should see lines of 1 thickness spaced by 1. Is this problem also related to a "mis-visualization" from matplotlib?

**Comment by adalca** [comment]
This is probably an issue with how we define 'spacing'. Right now, '1' means a a line at every voxel, so the image you get is all 1s (you can just print it's values to see this: `print(test_grid)` ). You'll get the effect you want with `bw_grid((5,5,5), 2)`. However, I think your intuition is right, and might change the code to add 1 to the passed in spacing.
