### ISSUE TITLE
The Dice_loss in pytorch

### ISSUE THREAD

**Issue by feng-gu** [voxelmorph/voxelmorph#196]
The Dice_loss in pytorch maybe wrong.

**Comment by adalca** [comment]
@feng-gu  It could be, it's certainly less well tested. Could you provide more information about what makes you say this?

**Comment by feng-gu** [comment]
pytorch/losses.py
In line 32: top = 2 * (y_true * y_pred, [1, 2, 3]).sum()   the 'tuple' object has no attribute 'sum'
In line33:  the input of the torch.max should be torch.max(input, dim)

**Comment by ahoopes** [comment]
Thanks for pointing this out @feng-gu. I have a feeling this was placeholder code initially since there's no way that function ever worked. I just added a fix (8e48fd11b515ba4fefe46aefc8a026e119acb540) to the legacy branch, and I also pushed a new dice loss class (7dd5432d992b8b1fbe5566e70f1dd7aaab86c2b1) to the master branch.
