### ISSUE TITLE
Dice confirmation 

### ISSUE THREAD

**Issue by Taariq78** [voxelmorph/voxelmorph#225]
Apologies for the frequent questions.

Regarding the Hard Dice, the labels are stored in a 1D array, correct?  If, for example, I have segmentations depicting two different structures, do I populate the 'label array' with two values that correspond with the given structures.

So, 'labels' will be of the form : [x,y] where x and y are equal to the intensity values of the 2 structures, respectively?

Or do I need to populate an array that's of the size of the image, such that each entry (each pixel) has a value associated with it?  Thank you, again.

**Comment by adalca** [comment]
@Taariq78 
in the hard dice function, the `label` parameter is a  list. For example, let's say you have 2 structures plus the background (so everything in the segmentation map is 0, 1 or 2). You would want to call the function with `labels=[1,2]` (because you likely want to explcude the background from the Dice computation).

**Comment by adalca** [comment]
p.s. even after an issue is closed because it's been answered, you can keep asking questions in it if your question is relevant, rather than starting a new issue
