### ISSUE TITLE
about use the test.py 

### ISSUE THREAD

**Issue by meggiezhou** [voxelmorph/voxelmorph#23]
thank you sir, I try to implement registration for my visible and frared pictures , i have made my own data set to .npy format ,but i have no label information how can i use the test.py to test the effect.

**Comment by meggiezhou** [comment]
infrared pictures

**Comment by adalca** [comment]
if you don't have any labels (segmentations) or landmarks, I think the best way would be to look at a few measures simultaneously:

1. Visually or with a metric (like mse) evaluate how good the images are aligned after you run voxelmorph. This is usually not a good idea to do by itself, since an algorithm could give you well-matching results with really irregular deformations. So:
2. Visually or with a metric (like a Jacobian determinant) look at the deformation field itself and make sure it's regular.

The best thing you could do is take some time to put some consistent landmarks on a few images (not many, even 5 would be helpful) and use the distance between landmarks as a measure of improvement.

**Comment by ZQYzqyZ** [comment]
Hi adalca:
              When I run the test.py or test.miccai2018.py,the code does not work properly, the reason for the error is as follows：

Using TensorFlow backend.
Traceback (most recent call last):
  File "C:/Users/Administrator/Desktop/voxelmorph-master/voxelmorph-master/src/test.py", line 74, in <module>
    test(sys.argv[1], sys.argv[2])
IndexError: list index out of range

Process finished with exit code 1
I don't know why the list index is out of range.So could you please give me some help.Thank you very much.
