### ISSUE TITLE
About training new model with pytorch version

### ISSUE THREAD

**Issue by leeh43** [voxelmorph/voxelmorph#232]
Hi, thank you for your great work of making registration platform with deep learning. I am currently training a model for abdominal registration. However, I do face some problems when the data is input into the training pipeline in the 3D UNet step.

I have resampled the moving image to the same resolution and dimension of the atlas target image. However it popped up some errors related to the size of feature. 
![image](https://user-images.githubusercontent.com/54121206/98090165-4a202a80-1e49-11eb-849b-5a4107ae0485.png)

The image dimension is 512 x 512 x 434 and the resolution is. 0.86 x 0.86 x 0.86. Do you mind to take a look what the issue is?

Thanks a lot!

**Comment by adalca** [comment]
@leeh43 

Because we use a UNet, the size of your image has to be a multiple of a power of 2, and in most cases (unless you modified something) a multiple of 32. You last dimension is 434, which is not a multiple of 32. You can pad your data by 7 on each side on that dimension, so that it's `512x512x448`. e.g. `vol = np.pad(vol, [(0,0), (0,0), (7, 7)], 'constant')`

**Comment by leeh43** [comment]
I forget about that. Thanks a lot!
