### ISSUE TITLE
MICCAI version   Pytorch

### ISSUE THREAD

**Issue by HP192080042** [voxelmorph/voxelmorph#236]
Thank you very much for your work. I would like to ask, is VoxelMorph's MICCAI version of Pytorch code available? I took a look and found that utils.py is incomplete. I would like to ask, when will the Pytorch version be distributed? Thank you

**Comment by adalca** [comment]
Hi @HP192080042 

The Pytorch version doesn't have the full MICCAI2018 version, but does have diffeomorphisms (and important part of the miccai2018 version). Right now, getting the full miccai version running in pytorch isn't a high priority for us since our preffered running setting for vxm is without sampling, and if necessary the miccai2018 is available in keras for anyone who needs to test it.

What did you need from the miccai version?
