### ISSUE TITLE
Unclear about "nb_features" dimensions

### ISSUE THREAD

**Issue by Kanyq** [voxelmorph/voxelmorph#254]
Hello, This might be a silly question but I'm trying to understand how to define the "nb_features" list of list, for my 3D input of shape (285, 285, 84).

I tried with the mentioned list for the "nb_features" in the tutorial for 3D brain scans but I'm getting an error saying: 
"A `Concatenate` layer requires inputs with matching shapes except for the concat axis. Got inputs shapes: [(None, 34, 34, 10, 32), (None, 35, 35, 10, 32)]"

**Comment by DanielAmsel-fau** [comment]
For every downsampling step in the encoder-part of the model the input gets downsampled by a factor of 2. In the decoder it gets upsampled by a factor of 2 the same amount of times. Due to the U-net style architecture concatination of inputs of related steps is performed. Therefore your input-sizes are required to be divisable by 2 to the power of n, where n is the number of up/down-sampling steps, to ensure this concatinations are possible.

**Comment by adalca** [comment]
Thanks @DanielAmsel-fau 

@Kanyq does that answer thre question? I'd like to move this to Discussions from Issues if that's done, then?

**Comment by Kanyq** [comment]
Yes that works for me. Thank you and you can go ahead and close this.
