### ISSUE TITLE
volexmorph encode features

### ISSUE THREAD

**Issue by Vive940219** [voxelmorph/voxelmorph#272]
@adalca 
In the earliest paper of the volexmorph model, the resize factor at the first 16 channels is 1.0
But in the /torch/network: the downsampling of the first 16 channels is already 0.5.
And in the up-arm, the final upsampling result cat with actually the input images, which is different from the paper.
Is this an update of the network structure?

**Comment by adalca** [comment]
@Vive940219  I'll ping @ahoopes since I know he recently just fixed some stuff in the pytorch version; 

But importantly, voxelmorph wasn't really about the specific architecture (number of layers/channels and so on), but the idea of doing unsupervised registration with nets -- the architecture itself in the paper is really what we could fit in memory with the GPUs of those times. The voxelmorph nets we use now (e.g. in [synthmorph](https://arxiv.org/pdf/2004.10282.pdf)) are much bigger, but that doesn't change the core idea!

**Comment by ahoopes** [comment]
This shouldn't be the case anymore in the dev-branch pytorch implementation. The original network was a bit of a simpler version of the tensorflow version.
