### ISSUE TITLE
about data input

### ISSUE THREAD

**Issue by zzx332** [voxelmorph/voxelmorph#29]
I have some problem with some input parameters of train_miccai2018.py:

1.What does data_dir and atlas_file mean?
2.If I want to register with my nii data set, how should these two parameters be set? 
“You might need to make a small change in the training file where train_vol_names is set, but that should be it.”This quoted from your answer,I don't know how to change train_vol_names.It would be better if you could explain it in detail.
3.Do I have to do other processing in addition to normalizing and cropping the input image?
Thank you very much

**Comment by adalca** [comment]
hi @zzx332 

1. the `data_dir` is a directory in which all your data (e.g. nifti or npz files) should be stored. the `atlas_file` refers to an atlas npz file to register the images to.
2. We currently default to `npz` files because this iss what we used in our experiments. We have a line in the training file: `train_vol_names = glob.glob(os.path.join(data_dir, '*.npz'))`. If you have nifti files, you would need to change this use `*.nii` instead of `*.npz`.
3. We tested voxelmorph on affinely-registered, normalized and cropped images, but of course it always depends on the data. I would try it like this and see how well it works.

**Comment by zzx332** [comment]
thank you for your reply,sorry to bother you again.
1.Is this program used to register many images into one image(atlas_file)?
2.If I have to register a lot of pairs of images(one-to-one correspondence),does it work?

**Comment by adalca** [comment]
@zzx332 
You mean VoxelMorph? Yes, voxelmorph is meant for registration (alignment). You can use VoxelMorph to learn to register images to an atlas, or image-to-image as well. FOr image-to-image you would simply need to change the image generator to give you two images instead of an image to an atlas.

**Comment by qiheihelan** [comment]
@adalca 
Hello.
Thank you for your previous reply and guidance.

I want to train my own network to achieve subject to subject registration.
Now I have my own data in voxelmorph/data11, the data format is nii,the data size is 240*160*192.
I have changed   train_vol_names = glob.glob(os.path.join(data_dir, '*.nii'))    in  train_miaccai2018.py.
I want to register  image-to-image. I know i need use miacci2018_gen_s2s. However,  I don't know how to use it.

1. I don't know how to change datagenertors.py to generate data correctly.
2. There are other places in the train_miccai2018.py file that need to be changed.
Can you give me specific instructions?

I look forward to your reply.  Thanks.

**Comment by adalca** [comment]
I'm not sure why you need to change datagenerators or train_miccai2018? What is your data, what makes you think you need to change the files?

**Comment by qiheihelan** [comment]
Hi.
 I do CT image registration of the lungs. I want to do subjet to subjet registration.
 In your reply four months ago you said
 'FOr image-to-image you would simply need to change the image generator to give you two images instead of an image to an atlas' .I don't know exactly what the change is. So the guess is to change two program files.
Sorry to bother you again. thank you.

**Comment by adalca** [comment]
those subject to subject generators are now implemented and published -- see e.g. `miccai2018_gen_s2s()` as you note above, so I don't think that needs to be modified. 

the main in `train_miccai2018` is that you should use `miccai2018_gen_s2s` (which does not require `atlas_vol_bs`) instead of `miccai2018_gen`.

**Comment by qiheihelan** [comment]
@adalca 
Hello. 
Excuse me, ask for help again.
My image size is 240, 160, 192. I changed gen to gen_s2s. But I get an error when running train_miccai208.py.


python train_miccai2018.py --gpu 0 ../data/train/


Using TensorFlow backend.
['../data/train/train2_vol.mgz', '../data/train/train3_vol.mgz', '../data/train/train4_vol.mgz', '../data/train/train5_vol.mgz']
2019-07-30 20:42:55.893991: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 AVX512F FMA
2019-07-30 20:42:55.903824: I tensorflow/core/platform/profile_utils/cpu_utils.cc:94] CPU Frequency: 2200000000 Hz
2019-07-30 20:42:55.909900: I tensorflow/compiler/xla/service/service.cc:150] XLA service 0x533e9e0 executing computations on platform Host. Devices:
2019-07-30 20:42:55.909976: I tensorflow/compiler/xla/service/service.cc:158]   StreamExecutor device (0): <undefined>, <undefined>
WARNING:tensorflow:From /usr/local/python3/lib/python3.6/site-packages/tensorflow/python/framework/op_def_library.py:263: colocate_with (from tensorflow.python.framework.ops) is deprecated and will be removed in a future version.
Instructions for updating:
Colocations handled automatically by placer.
WARNING:tensorflow:From /usr/local/python3/lib/python3.6/site-packages/tensorflow/python/ops/array_grad.py:425: to_int32 (from tensorflow.python.ops.math_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Use tf.cast instead.
Epoch 1/1500
2019-07-30 20:43:17.951446: W ./tensorflow/core/grappler/optimizers/graph_optimizer_stage.h:241] Failed to run optimizer ArithmeticOptimizer, stage RemoveStackStridedSliceSameAxis node diffflow/map/while/strided_slice. Error: Pack node (diffflow/map/while/stack_3) axis attribute is out of bounds: 3
...
2019-07-30 20:43:23.126180: W ./tensorflow/core/grappler/optimizers/graph_optimizer_stage.h:241] Failed to run optimizer ArithmeticOptimizer, stage RemoveStackStridedSliceSameAxis node diffflow/map/while/strided_slice_2. Error: Pack node (diffflow/map/while/stack_3) axis attribute is out of bounds: 3
Traceback (most recent call last):
  File "train_miccai2018.py", line 192, in <module>
    train(**vars(args))
  File "train_miccai2018.py", line 147, in train
    verbose=1)
  File "/usr/local/python3/lib/python3.6/site-packages/keras/legacy/interfaces.py", line 91, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/python3/lib/python3.6/site-packages/keras/engine/training.py", line 1418, in fit_generator
    initial_epoch=initial_epoch)
  File "/usr/local/python3/lib/python3.6/site-packages/keras/engine/training_generator.py", line 217, in fit_generator
    class_weight=class_weight)
  File "/usr/local/python3/lib/python3.6/site-packages/keras/engine/training.py", line 1217, in train_on_batch
    outputs = self.train_function(ins)
  File "/usr/local/python3/lib/python3.6/site-packages/keras/backend/tensorflow_backend.py", line 2715, in __call__
    return self._call(inputs)
  File "/usr/local/python3/lib/python3.6/site-packages/keras/backend/tensorflow_backend.py", line 2675, in _call
    fetched = self._callable_fn(*array_vals)
  File "/usr/local/python3/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1439, in __call__
    run_metadata_ptr)
  File "/usr/local/python3/lib/python3.6/site-packages/tensorflow/python/framework/errors_impl.py", line 528, in __exit__
    c_api.TF_GetCode(self.status.status))
tensorflow.python.framework.errors_impl.InvalidArgumentError: indices[47,48,4] = -2147483648 is not in [0, 860160)
     [[{{node flow-int/map/while/GatherV2_14}}]]

I don't know what is wrong? So come here again.Thank you very much for your continued help.

Looking forward to your reply.

**Comment by adalca** [comment]
hi @qiheihelan , can you please format your code so it's more readable here (see https://help.github.com/en/articles/creating-and-highlighting-code-blocks)

This error is complicated, but to me it hints at the fact that not all of your data fed to the model is the same size. Are you sure all the images were `240x160x192` ?

**Comment by qiheihelan** [comment]
@adalca 
Hello.
I confirm that my image is the same size. I also tried to change the image size. For example, 160*160*208.( I opened the image with ImageJ. The 15th piece shows 15/208; 160.00*160.00mm (160*160); 16-bit 10MB).  But the above error will still occur.
I have not found what is the reason. So I also want to ask you to help think about it.
Thank you for your help.

**Comment by qiheihelan** [comment]
@adalca 
Hello.
I confirm that my image is the same size. I also tried to change the image size. For example, 160160208.( I opened the image with ImageJ. The 15th piece shows 15/208; 160.00160.00mm (160160); 16-bit 10MB). But the above error will still occur.
I have not found what is the reason. So I also want to ask you to help think about it.
My images are not normalized and affine transformed. Will this be the cause of the error?
Thank you for your help.

**Comment by adalca** [comment]
what does 15th piece means?

I wouldn't try to change the size of the image -- just make sure the original image size is the same *for all images*.

Googling this error a bit makes it seem like there is an issue with the tensorflow CPU implementation -- are you running on a GPU or CPU? what `tf` version?
see e.g. https://github.com/tensorflow/models/issues/4900

**Comment by qiheihelan** [comment]
@adalca
Hi.
I running on a GPU and  tf version is 1.13.1.
 When I feed the two images you provided as a pair of inputs (e.g. atlas_nomal.nii as moving image,and its duplicate as fixed), the program works fine. But when I feed my own two image, an error occurs. So it may still be because the image is not processed correctly.
so，venture to ask a question, could I  send two images I processed to your mailbox. Could you help me see what is wrong?  
Thank you very much for your continued help. I will continue to improve and strive to get my results as soon as possible.
Thanks.

**Comment by adalca** [comment]
you can post screenshots of the images here. Here's some things to do:

(1) what is the min and max intensity in your images?
(2) loop through all your images, and print the shape of the data, and the intensity statistics (min, max, mean, `dtype`, etc)?
