### ISSUE TITLE
Questions about ANTs

### ISSUE THREAD

**Issue by ZexinYan** [voxelmorph/voxelmorph#3]
I have some questions about your paper.
In your paper, you have provided the performance of `Affine only` and `ANTs`, could you share your scripts about how to get such results?

**Comment by adalca** [comment]
We've run affine registration to talairach using FreeSurfer (which we also used for preprocessing like skull stripping).  We used the `recon-all` for this, which performs a number of analysis steps, since we use the data for various other projects (see  https://surfer.nmr.mgh.harvard.edu/fswiki/recon-all  for more details). However, you can probably get away with using http://freesurfer.net/fswiki/talairach if all you'd like to do is the affine registration

In general, ANTs will also do affine registration, and if that's the main operation you're interested in, perhaps you should simply use ANTs. You need to set the number of affine iterations to non-zero (e.g. `1000x1000x1000x1000`), and the number of deformable iterations to 0. 

Finally, to run deformable registration with ANTs (if you've performed affine separately), use 0 affine iterations, as follows.

Assuming `ants_cmd` is the path to the `ANTS` command, `output_core` is an output folder, `fixed_file` and `moving_file` are paths to the appropriate files, such as affinely registered subject and atlas, you can use: 
```
${ants_cmd} 3 -m CC[${fixed_file},${moving_file},1,4] -t Syn[0.25] -o ${output_core}/ants --number-of-affine-iterations 0x0 -i 201x201x201 -r Gauss[9,0.2]
```
