### ISSUE TITLE
About the affine transformation between moved image and the fixed image 

### ISSUE THREAD

**Issue by zhangliukun** [voxelmorph/voxelmorph#30]
Hello, I have read your paper and your work is very nice.
I would appreciate it if you could answer my questions. There is no affine transformation in the test image in your paper. I don't know whether the code can handle the situation if there has a violent affine transformation between the fixed and moved image?

**Comment by zhangliukun** [comment]
```python 
# warp the source with the flow
 y = nrn_layers.SpatialTransformer(interp_method='linear', indexing=indexing)([src, flow])
```
src[160,192,224,1]
flow[160,192,224,3]
I also don't understand why flow's last dimension is 3, what's the meaning?
I wonder whether it can be other value such 2 or 4.

**Comment by adalca** [comment]
hi @zhangliukun 

Please see #3 for a discussion of the affine step

The last channel of the displacement field has to be the number of dimensions in the volume, because it tells your volume how to move in each dimension. So for a 2D volume (an image) it has to be 2, for a 3D volume (like MRI) it has to be 3.
