### ISSUE TITLE
Difference between scan_to_scan and scan_to_atlas

### ISSUE THREAD

**Issue by ElegantLin** [voxelmorph/voxelmorph#341]
Dear author, thanks for your great work. I am using the `dev` and `master` branches. I want to know the difference between scan_to_scan and scan_to_atlas. I saw some of the users used the `scan_to_atlas` in the scene where there are moving images (scan) and fixed images (atlas). Did they use the function correctly? If they use the function in the right way, could you please tell me or give me an example of `scan_to_scan`?

Thanks a lot!

**Comment by adalca** [comment]
`scan_to_scan` refers to registering two scans together, so the generator will grab two random scans and feed them to the model. I'm not quite sure what you mean by example for this -- e.g. when someone might want to use this?

`scan_to_atlas` will randomly sample one scan, while the other image will always be the atlas.  

So yes, the use you are referring to seems correct.

**Comment by ElegantLin** [comment]
Dear Adrian, thanks for your quick and clear reply. I have two questions and hope you can help me.

1. Since making moving images to the fixed ones is `scan_to_atlas`, why is the atlas only one volume? For example, there are 30 subjects in my datasets and every subject has a pair of moving and fixed. I think the `scan_to_atlas` does not fit the scene.

2. For the example, I mean that since fixed-moving is the `scan_to_atlas`. Is there some setting like moving-moving which is suitable for `scan_to_scan`?

Thanks for your explanation.

**Comment by adalca** [comment]
*moving* and *fixed* are just terminologies we use in the model, in some sense it's a separate concept from the generators. It's just saying that the model *moves* one image to "match" the other. 

The generators are python constructs that feed a pair of images to the models, which are then treated as *moving* and *fixed*. How the generators come up with the two images is up to the generators. We have two generators prepared for you, assuming you have a list of 30 images and one atlas:

`scan_to_scan` this will randomly grab two images from the 30. Training a model with such a generator means the generator will assume that both the *moving* and *fixed* images are just random scans, and will learn to register scans together.
`scan_to_atlas` will randomly grab one image from the 30, and use the atlas as the other image. A model trained with this generator will only know how to register different scans *to an atlas*. 

Those are essentially two different ways to use registration.

If you have a situation where you have 30 **subjects**, and each subject has two images, you'd need to write your own generator (since I don't think we have one written in the `dev` branch, right @ahoopes ?), although it should be fairly easy. Basically (1) choose one subject at random, (2) choose two scans from that subjets.

**Comment by ElegantLin** [comment]
Sure! Thanks for your patience and your guide. I also think I should implement it myself, making it randomly select `batch_size` subjects and making the `input_vol` and `output_vol` correct.

Thanks for your help again!

**Comment by ahoopes** [comment]
> since I don't think we have one written in the dev branch, right?

Right! You'll have to implement your own generator if each subject has two images. But that should be relatively straightforward if you follow `vxm.generators.scan_to_scan` as a template

**Comment by Irisssssa** [comment]
> Sure! Thanks for your patience and your guide. I also think I should implement it myself, making it randomly select `batch_size` subjects and making the `input_vol` and `output_vol` correct.
> 
> Thanks for your help again!
Hi!Thanks for your question.I'm facing with the same scene now.And I see the difference between scan_to_scan and scan_to_atlas now!There are also 30 objects(for example) in my dataset and each object includes one moving image and one fixed image.Now I want to align and hope you can help me.Have you implemented your generator?Could you please send me the code?

**Comment by Irisssssa** [comment]
> Sure! Thanks for your patience and your guide. I also think I should implement it myself, making it randomly select `batch_size` subjects and making the `input_vol` and `output_vol` correct.
> 
> Thanks for your help again!

Hi!Thanks for your question.I'm facing with the same scene now.And I see the difference between scan_to_scan and scan_to_atlas now!There are also 30 objects(for example) in my dataset and each object includes one moving image and one fixed image.Now I want to align and hope you can help me.Have you implemented your generator?Could you please send me the code?

**Comment by adalca** [comment]
as @ahoopes said, `vxm.generators.scan_to_scan` is a good example -- it's just that instead of getting two random scans, you get one ranom object from your 30, and then get the two images for that object (all of which depends on how these objects are stored, etc). See https://github.com/voxelmorph/voxelmorph/blob/5b8475364f3bc1d0742f2d1f0f493f0b5ab8ac01/voxelmorph/generators.py#L71

**Comment by Irisssssa** [comment]
> as @ahoopes said, `vxm.generators.scan_to_scan` is a good example -- it's just that instead of getting two random scans, you get one ranom object from your 30, and then get the two images for that object (all of which depends on how these objects are stored, etc). See
> 
> https://github.com/voxelmorph/voxelmorph/blob/5b8475364f3bc1d0742f2d1f0f493f0b5ab8ac01/voxelmorph/generators.py#L71

I see!Thanks for your guide!I'm trying to implement it using scan_to_scan^_^.
