### ISSUE TITLE
You are trying to load a weight file containing 12 layers into a model with 10 layers.

### ISSUE THREAD

**Issue by zoujinger** [voxelmorph/voxelmorph#36]
hello, I have problem with network layers
here is the code:
vol_size=(160,192,224)
nf_enc=[16,32,32,32]
nf_dec=[32,32,32,32,32,16,16,3]
net = networks.unet_core(vol_size, nf_enc, nf_dec)
net.load_weights(os.path.join(vm_dir, 'models', 'xy', 'vm2_cc.h5'))

but there is always the error, since I cannot find unet in networks, I use unet_core
![image](https://user-images.githubusercontent.com/27009979/56571751-2fcc8600-65f0-11e9-9a69-b5f49e5bca3e.png)

**Comment by zoujinger** [comment]
if I use unet, then error:
![image](https://user-images.githubusercontent.com/27009979/56572027-c436e880-65f0-11e9-99db-5df1ae4997fb.png)

**Comment by adalca** [comment]
the (first) error is saying that the weights file has more layers than the net you created. This is because, as we show in the train.py file, we use the architecture in the `cvpr2018_net` , which is the `unet_core` plus a couple of more layers. So, please try using the `cvpr2018_net` architecture and see if this persists.

**Comment by zoujinger** [comment]
thanks a lot!
I use cvpr2018_net, but still have error:
![image](https://user-images.githubusercontent.com/27009979/56709105-278c5c00-6752-11e9-8980-ad2057081c23.png)

![image](https://user-images.githubusercontent.com/27009979/56709134-3ffc7680-6752-11e9-9c58-aeb84f1216cd.png)

Is there anything wrong with the version of TensorFlow or Keras?
Here is my version:
python 3.6.4
tf  1.3.0
keras 2.0.6

**Comment by balakg** [comment]
you may be loading in weights from the vm1 model into the network architecture for vm2. Try changing the nf_enc and nf_dec variables to the vm1 architecture and see if that works.

**Comment by zoujinger** [comment]
Thanks!
I changed to the vm1 architecture, but still doesn't work.
vol_size=(160,192,224)
nf_enc=[16,32,32,32]
nf_dec=[32,32,32,32,8,8,3]

![image](https://user-images.githubusercontent.com/27009979/56710939-1bf16300-675b-11e9-83a4-78bdd1728b19.png)

**Comment by zoujinger** [comment]
![image](https://user-images.githubusercontent.com/27009979/56712625-b6ed3b80-6761-11e9-89cc-6ad77d0744a2.png)
this setting works ,but there is something wrong with the result 
the dimension of deformation is wrong, I am a beginner. Would you please give me some advice about where I can change
thanks a lot 

![image](https://user-images.githubusercontent.com/27009979/56712781-3ed34580-6762-11e9-83ab-a8559dad81e7.png)

**Comment by adalca** [comment]
@zoujinger, 

the miccai version of voxelmorph returns the velocity field, not the deformation field. Thi sis an intermediate field that is used to reconstruct the deformation field. By default, the velocity field is only computed every 2 pixels, which is why you get the different size.

I would recommend sticking to the cvpr version for now and seeing why it fails. Could you see if simply doing `keras.models.load_model(...)` works with the `cvpr2018_vm2_cc.h5` file, and the vm2 parameters?
