### ISSUE TITLE
What is the role of vm1.h5 and vm2.h5？

### ISSUE THREAD

**Issue by JianshuiChen** [voxelmorph/voxelmorph#39]
Dear adalca,
I have some questions when I train my model with your code. I used my trained model to register results that were unsatisfactory. I guess this may be that I used the default pre-training model (```voxelmorph/models/cvpr2018_vm1_cc.h5```, ```voxelmorph/models/cvpr2018_vm1_l2.h5```, ...) in your code. Therefore, if it's available to train my network with the default pre-training model based on my dataset? And what is the role of vm1 and vm2?
Thanks!!!

**Comment by adalca** [comment]
hi @JianshuiChen ,

Our CVPR2018 and MICCAI2018 models are trained with a specific data type and processing pipeline (described in the paper). Are you using ismilar data and processing? If not, I do recommend you train a new network (probably best to train from scratch, in fact, so there are not biases, but you should feel free to initialize with our models.).

vm1 and vm2 are simply different architectures, vm2 is slight bigger which takes longer to train but gives slightly better results. We recommend you use `vm2` or `vm2double`.

**Comment by leilamou** [comment]
hi @adalca 
I am a collaborator of @JianshuiChen . Our data (fundus images) is different from yours. So what we need to do is train a new registration model for the fundus image. We used ```vm2``` as the pre-training model during training, but the model's prediction results were ugly. We are wondering if not using your pre-training model will make the registration result better. In addition, how do we change the code so that we don't use any pre-trained models? We are a newcomer in Tensorflow.
thank you very much!

**Comment by adalca** [comment]
@leilamou 

Yes, the models trained on T1 MRI images are likely to do bad on Fundus images. To train a new model from scratch, simply set `load_model_file` parameter to empty. e.g. `--load_model_file ""`

**Comment by JianshuiChen** [comment]
![](http://ww1.sinaimg.cn/large/005CmS3Mly1g2q6htkcdgj30bu08lglq.jpg)
The left is color fundus and the right is OCT.
