### ISSUE TITLE
The following are what I think should ba modify.

### ISSUE THREAD

**Issue by DownStone** [voxelmorph/voxelmorph#40]
- When running `python /data/afei/voxelmorph/src/train_miccai2018.py /data/afei/voxelmorph/data --gpu 3 --model_dir /data/afei/voxelmorph/models/models_1 --atlas_file /data/afei/voxelmorph/data/atlas_norm.npz --load_model_file /data/afei/voxelmorph/models/miccai2018_10_02_init1.h5`, it's wrong with `X = np.load(datafile)['vol_data']` and right with `X = np.load(datafile)['vol']` in `datagenerator.py`.
 - And the folIwing are my code and content in `../data/atlas_norm.npz`:
```python
import numpy as np
test=np.load('/data/afei/voxelmorph/data/atlas_norm.npz')
print(test.files)`
# ['vol', 'seg', 'train_avg']
```
| filename | content |
| ------ | ------ |
| meanstats_T1_WARP.npz | ['init_mu', 'init_std'] |
| test_vol.npz | ['vol_data'] |

So I think u should modify your code.

**Comment by adalca** [comment]
hi @DownStone,

Thanks for your note.

Except for the atlas, all of our data is stored in the `vol_data` variable in npz files, as it is in `test_vol.npz`. The old code in `datagenerator.py` assumes this. 

My guess is you put the data in a variable name `vol` instead of `vol_data`.

I've changed the generators in `datagenerator.py` to enable specifying the numpy variable name, so you can set it to whatever you want when you call, for example, `example_gen`. This should help with your particular setting. FOr example, you'll probably want to set `np_var = 'vol'`.
