### ISSUE TITLE
Get predicted deformation field moving -> fixed

### ISSUE THREAD

**Issue by annareithmeir** [voxelmorph/voxelmorph#560]
I am registering a dataset with Hypermorph (moving images to fixed) and noticed that the prediction result from the registration model is the inverse, i.e. from fixed to moving.
I have seen the example colab notebooks for obtaining the inverse deformation for affine deformations.
How do I obtain the inverse of a non-parametric deformation, i.e. a displacement field?

**Comment by adalca** [comment]
> noticed that the prediction result from the registration model is the inverse, i.e. from fixed to moving.

Can you expand on what this mean? The deformation field has to be in the space of the fixed image indeed, because it has to *pull* the moving image to that space. 

perhaps I am misunderstand what you mean, though

We also work with diffeomorphisms in certain models, and computing the inverse field is trivial in that scenario. A bit harder, but still possible. otherwise. Can you tell us exactly which model you are using?

pinging the HyperMorph author @ahoopes , but I know he's quite busy until the CVPR deadline :)

**Comment by annareithmeir** [comment]
thanks for the quick reply!
I am using the standard hypermorph model and not constraining it to be diffeomorphic. 
I want to visualize how the points in the moving image are "pushed" towards the fixed image, this is why i am looking for the inverse.

**Comment by adalca** [comment]
Okay, I wrote a quick (not well tested) tutorial here: https://colab.research.google.com/drive/1juAJRYhPPDNbO9yRtlc0VGhbIFSuhpJ2?usp=sharing

**Comment by annareithmeir** [comment]
Ah perfect, thanks a lot!! :)
