### ISSUE TITLE
pytorch pre-train file

### ISSUE THREAD

**Issue by wangnanv5** [voxelmorph/voxelmorph#583]
hello,there are only have tf model files,can you provide pytorch pre-train files? 
thank you!

**Comment by amirshamaei** [comment]
I need pytorch pretrained files as well.

**Comment by lchauvin** [comment]
Same here

**Comment by amirshamaei** [comment]
Are you up to train it and release the pre-trained file?

**Comment by lchauvin** [comment]
I wanted to, but for now SynthMorph code for training on synthetic data is only available for Tensorflow.

If I time in the given days, I will try to migrate it to PyTorch, then it would be easy to generate some pre-trained models.

**Comment by amirshamaei** [comment]
@lchauvin thank you.
Have you seen this: https://github.com/Hsankesara/VoxelMorph-PyTorch/blob/master/README.md

I am trying to get a master student to do this. I think having it as a library would be helpful when we want to train end to end as well.

**Comment by adalca** [comment]
@avnishks has kindly trasnformed the synthmorph model to pytorch. I'll try to loosely test it in the next day or two on a few images, and if it looks reasonable I'll post it here.

**Comment by lchauvin** [comment]
@amirshamaei Yes, but I'm not sure about this, because VoxelMorph seems to have a pytorch implementation now (I don't know if it comes from this repo). The only thing is that it's only VoxelMorph, not SynthMorph, which would make it easier to train as we can generate synthetic data. I'll try to have a look at converting this: 

https://colab.research.google.com/drive/1zaDnAJGUokS0knqWttuTgrRJMb6zxukI?usp=sharing#scrollTo=4X5X1R1eCB5J

**Comment by amirshamaei** [comment]
@adalca Thank you. Looking forward to using that!
