### ISSUE TITLE
step of register two mri images

### ISSUE THREAD

**Issue by BoyuanJiang** [voxelmorph/voxelmorph#61]
Hi, I have some 7T and 3T MRI image pairs. For the shape of 3T MRI image is [256,176,256] and the shape of 7T MRI image is [310,314,208], that is to say, 3T MRI image has 256 slices and 7T MRI image has 208 slices. If I want to train a model to register 3T MRI image to 7T MRI image, what should I do first to prepare my dataset? I am a novice in this area, any suggestions are welcome. Thanks

**Comment by adalca** [comment]
I would try the following:
1. register each pair affinely (e.g. each 7T to 3T) with a different algorithm (e.g. ANTs). Note we have an internal affine VoxelMorph, but are still testing it before releasing it.
2. register each affine-registered-7T to the 3T with VoxelMorph. This can be done by just changing the data generator for VoxelMorph such that instead of giving an (Atlas, image) pair, you give the (Affine-registered-7T, 3T) pair.

**Comment by BoyuanJiang** [comment]
can you tell methe ants command to register each pair affinely (e.g. each 7T to 3T)? Thanks

**Comment by adalca** [comment]
The ANTs registration command tools have changed quite a bit recently, I would recommend looking closely at the documentatin: https://github.com/ANTsX/ANTs/wiki/Anatomy-of-an-antsRegistration-call
