### ISSUE TITLE
Working with image patches

### ISSUE THREAD

**Issue by jeanyves-yang** [voxelmorph/voxelmorph#69]
Hello, 

I was wondering if it is possible to give image patches instead of whole images as inputs to the network. The spatialtransformer layer seems to require to know the input shapes, which prevent from giving patch sizes at training time and whole image size at test time.

Thanks

**Comment by adalca** [comment]
Yes, you can do this without a problem. The model weights learned from a patch model can be loaded into a full model, since the weights belong to the convolution layers only.

So you can:
1. create and train model with patches --> save weights
2. create model for full image and load saved weights from patch model.

Of course, I'm not certain how well this will work since training and testing are slightly different, but it's certainly doable.

**Comment by John1231983** [comment]
@jeanyves-yang: Do you solve the problem? if you use the image-patches, such as 32x32x32 or 64x64x64 then how do you achive the final moved image? As far as I know, it should be used over-lapping between patches with stride >1 to construct the whole prediction from the prediction of patches.

**Comment by jeanyves-yang** [comment]
@John1231983 For training, it did not matter, I trained with overlapping patches. For prediction/inference, I performed it on the whole image (I thought reconstructing from patches was slower than just infering on the whole image).

**Comment by adalca** [comment]
@jeanyves-yang @John1231983 yup this sounds good to me -- at training, you can just load the weights into a model that's the full size.

I would be careful about training with patches, since having the correct deformation at the edges of the images is hard in that case.

**Comment by John1231983** [comment]
>I performed it on the whole image (I thought reconstructing from patches was slower than just infering on the whole image).

@jeanyves-yang : I agree with you that we can train with overlapping patches. The learned weight is for the patch size (i.e 64x64x64). But it is not clear that how can we use the learned weight to predict the deformation if the input is whole image. Because the learned weight is for patch only.

For example, the input image is 256x256x256. We train the network with cropped input size of 64x64x64 (patch-based). Then the trained model is for the cropped image, instead of whole image (256x256x256).

**Comment by adalca** [comment]
@John1231983 The weights are all convolutional, so they are invariant to model size. True, they learned on patches, but conceptually they learned something that is spatially invariant

So you can do something like 
```
model_64_patches = cvpr_2018([64,64,64], ...)
model_64_patches.fit(patches)

model_256 = cvpr_2018([256,256,256], ...)
model_256.load_weights(model_64_patches.get_weights())
model_256.predict(...)  # registration of full image)
```

**Comment by John1231983** [comment]
Thanks. I tried it and the result is too bad.

For question about edge
>I would be careful about training with patches, since having the correct deformation at the edges of the images is hard in that case.
Assume that we have two crops (left:moving, right: fixed). So, we can see that in the boundary of the crop region (top-left, top-bottom....), these pixels may not move because it is in outer regions. It means the deformation field at the position will learn to zero. TO solve it, do you think we need to add zero paddings to the crop images, so that the foreground region can expanding...
![Screenshot from 2019-09-04 12-59-35](https://user-images.githubusercontent.com/24875971/64275622-09124a80-cf14-11e9-9162-dfd2ba59a234.png)

**Comment by John1231983** [comment]
@jeanyves-yang  and @adalca : I have found a paper that used the patch-based approach for image registration. Actually, it is very similar your network, just used patches instead of full image. And it used ground-truth deformation (I guess from ants)
https://www.sciencedirect.com/science/article/pii/S1361841519300283

In this paper, he mentioned that he downed image resolution from 64x64x64 to 24x24x24 and the prediction deformation is in the downing resolution 24x24x24. However, it is not clear how he can compute the spatial loss between moving and target image because the patch size is 64x64x64, while deformation field is 24x24x24. Let's me know if you find the answer

For testing, he combined predicted 24x24x24 deformation field without padding.

**Comment by adalca** [comment]
sorry, i probably wasn't clear

I was saying above how you *can* do it, now how you *should* do it :) In general, I don't think you should train on patches! there are all sorts of issues. Padding won't help, then the network will try to enforce the edge between the image and the background to fit the edge in the second image, which is bad. 

The main solution I see is to have the loss operate only over the center of the patch. e.g. if the patch is 64^3, then have the loss operate only over the center 32^3 or 16^3.

But the main alternative is to have the biggest volume your GPU memory can handle, this has always worked best for us.

**Comment by John1231983** [comment]
@adalca : Thanks for value discussion. I just want to make clear the meaning of
>since having the correct deformation at the edges of the images is hard in that case.
What do you mean the edge of the image? Is edge of bounding box that defined the patches? The reason is hard to correct deformation because it cannot expand in the edge region, right?

**Comment by adalca** [comment]
yes, that edge, and that's one reason -- but there's all kinds of reasons (at the edges the filter responses also get a bit whacky, for example), etc.

**Comment by John1231983** [comment]
I see. @jeanyves-yang : DO you have a good reason why do you want to train with patches? If GPU memory is limited, you can reduce the network depth.

If memory is not problem and you want to use patch for some reason, why not train it with full image size and crop the patch in the deformation field (obtained by training on full image size)?
